### ISSUE TITLE
Warning when supplying an Array

### ISSUE THREAD

**Issue by franciscoamado** [GuillaumeCisco/react-json-prettify#3]
Hi there 👋🏻

Thank you for building this!

I've been using it and getting the following warning when supplying an Array of objects to prettify

> Warning: Failed prop type: Invalid prop `json` of type `array` supplied to `JSONPretty`, expected `object`.

It still resolves to a valid JSON with no problems.

Is there any way to silence this warning?

Thank you again 🙏🏻

**Comment by GuillaumeCisco** [comment]
Thanks a lot Francisco.

I did not know someone else used this project :)
The modification to your request is very easy.
This is about prop validation https://github.com/GuillaumeCisco/react-json-prettify/blob/master/src/index.js#L142
We can replace by something like PropTypes.OneOf(PropTypes.shape({}), PropTypes.arrayOf(PropTypes.any))

Unfortunately, I'm on vacation for a few days in the mountains and won't be able to use a computer before Tuesday.
I'll look deeply this issue when I'll come back ;)

By the way, this warning should only appear in dev environment.

I will take time to also update the dependencies of this project.

**Comment by GuillaumeCisco** [comment]
Code has been updated ;)
New 0.1.5 version has been published on npm

**Comment by franciscoamado** [comment]
Thank you so much for the support!

Cheers 👋🏻
