### ISSUE TITLE
Dynamic Colors For Values

### ISSUE THREAD

**Issue by naumanzchaudhry** [GuillaumeCisco/react-json-prettify#5]
@GuillaumeCisco  Thanks much for the package.

Currently over-riding theme styles accepts css basic colors. How can I assign colors based on some condition? Something like below. 

```
const customTheme = {
  ...theme,
  value: {
    ...theme.value,
    string: theme.value.string === 'donor' ? 'red': 'green'
  }
}
```

**Comment by GuillaumeCisco** [comment]
i don't really understand your issue.
Absolutely no themes in `react-json-prettify` use a `'donor'` value for their `value.string`.

Are you much testing with the values of your json???
You'd want to modify the color from the json value?
If yes, this is not supported yet, but could be easily added as a new feature

**Comment by naumanzchaudhry** [comment]
@GuillaumeCisco Yes basically, I am trying to put a condition to a particular value. Whenever my json has that particular value. I'd want to assign a color to that.

**Comment by GuillaumeCisco** [comment]
I've just published a new version of the package, you will now be able to use conditionnal function on your json values for basic types.
